import { NextSeo, FAQPageJsonLd } from 'next-seo'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { usePostHog } from 'posthog-js/react'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Alert from '@/components/Alert'
import LoadingSpinner from '@/components/LoadingSpinner'
import RegisterCTA from '@/components/RegisterCTA'
import FreeToolsGrid from '@/components/FreeToolsGrid'
import { StarRating } from '@/components/StarRating'
import { getRating } from '@/lib/tools'
import ToolsSignupModal from '@/components/ToolsSignupModal'
import CarbonAd from '@/components/CarbonAd'
import {
  ChatBubbleLeftRightIcon,
  AcademicCapIcon,
  ClipboardDocumentCheckIcon,
  ExclamationTriangleIcon,
  LightBulbIcon,
  RocketLaunchIcon,
  ShieldCheckIcon,
  SparklesIcon,
  CheckBadgeIcon,
  InformationCircleIcon,
  CheckIcon,
} from '@heroicons/react/24/outline'
import { ClipboardDocumentIcon } from '@heroicons/react/24/solid'
import { unified } from 'unified'
import remarkParse from 'remark-parse'
import remarkGfm from 'remark-gfm'
import remarkRehype from 'remark-rehype'
import rehypeStringify from 'rehype-stringify'

const loadingText = [
  'Generating high-quality answers with advanced AI support...',
  'Analyzing your question context for the perfect reply...',
  'Organizing structured insights from our AI answer generator...',
  'Refining tone, clarity, and supporting details...',
  'Delivering your optimized AI-generated answer...',
]

const LoadingText = () => {
  const [index, setIndex] = useState(0)

  useEffect(() => {
    const interval = setInterval(() => {
      setIndex((prev) => {
        if (prev < loadingText.length - 1) {
          return prev + 1
        }
        clearInterval(interval)
        return prev
      })
    }, 3500)

    return () => clearInterval(interval)
  }, [])

  return <p className="animate-pulse text-sm text-white">{loadingText[index]}</p>
}

const tones = [
  {
    name: 'Balanced Professional',
    emoji: '🤝',
    description: 'Clear, confident answers that work for most situations',
  },
  {
    name: 'Academic',
    emoji: '🎓',
    description: 'Formal explanations with citations-ready structure',
  },
  {
    name: 'Friendly',
    emoji: '😊',
    description: 'Approachable and conversational answer style',
  },
  {
    name: 'Persuasive',
    emoji: '🎯',
    description: 'Compelling responses ideal for convincing stakeholders',
  },
  {
    name: 'Supportive',
    emoji: '💡',
    description: 'Empathetic tone for customer answers and help docs',
  },
  {
    name: 'Technical',
    emoji: '🛠️',
    description: 'Precise answers for engineers, IT teams, and analysts',
  },
]

const answerLengths = [
  {
    name: 'Concise',
    description: 'Fast short-form answers for quick replies and quizzes',
  },
  {
    name: 'Comprehensive',
    description: 'Balanced depth with key takeaways and context',
  },
  {
    name: 'In-Depth',
    description: 'Detailed explanations with supporting rationale',
  },
]

const formats = [
  {
    name: 'Structured Paragraphs',
    description: 'Polished paragraphs ideal for essays and documentation',
  },
  {
    name: 'Bullet Points',
    description: 'Skimmable answer generator AI output for summaries',
  },
  {
    name: 'Step-by-Step',
    description: 'Procedural format for tutorials and troubleshooting',
  },
]

const faqs = [
  {
    question: 'What is an AI answer generator?',
    answer:
      'An AI answer generator is a free online tool that uses advanced language models such as GPT-5 to analyze questions and produce complete, reliable answers instantly. Simply enter your question, optionally add context, and the answer AI generator will craft a response in your preferred tone and format.',
  },
  {
    question: 'Is DocsBot\'s AI answer generator really free with no sign up?',
    answer:
      'Yes, you can use our AI answer generator free with no sign up required. Enjoy generous daily usage powered by the same advanced AI technology that drives DocsBot. Create unlimited responses, then upgrade for higher limits and team collaboration when you are ready.',
  },
  {
    question: 'What are the daily rate limits?',
    answer:
      'Free visitors can generate 3 answers daily, free DocsBot users get 6, and paid DocsBot plans multiply those limits by 5x for extra capacity.',
  },
  {
    question: 'Can this answer generator AI help with tests and homework?',
    answer:
      'Our AI test answer generator is designed to explain concepts clearly so you can learn faster. Paste your study prompts or quiz questions to receive step-by-step guidance, citations-ready context, and alternative explanations tailored to your learning style with GPT-5-level reasoning.',
  },
  {
    question: 'How accurate are the answers generated by this tool?',
    answer:
      'The AI generator answers are powered by state-of-the-art AI models and tuned instructions to stay factual and relevant. However all LLMs are subject to hallucinations and responsesshould be reviewed for accuracy. For mission-critical content, we recommend signing up for DocsBot and to ground answers in your own DocsBot-trained knowledge base for perfect accuracy.',
  },
  {
    question: 'Which AI model powers this free answer generator?',
    answer:
      "DocsBot routes your prompts through OpenAI's GPT-5 model with reasoning so every AI generated answer benefits from cutting-edge knowledge. For the most accurate, source-grounded results, train a DocsBot agent on your own documentation and let GPT-5 respond with citations to your content.",
  },
  {
    question: 'Can I embed this AI answer generator on my website?',
    answer:
      'Absolutely. Sign up for DocsBot to build a custom AI answer generator that is trained on your website, documentation, or knowledge base. Share it publicly, embed it anywhere, and let visitors ask questions with instant, accurate answers.',
  },
  {
    question: 'Is my data private when using this AI answer generator?',
    answer:
      'Yes, your privacy is protected. We never store your questions, context, or generated answers. All processing happens securely and your data is not retained after generation. For enterprise-grade privacy controls, audit logs, and data governance, upgrade to DocsBot with custom trained agents.',
  },
]

const benefits = [
  {
    name: 'Instant multi-format answers',
    description:
      'Switch between paragraph, bullet, or step-by-step outputs and let our AI answer generator adapt immediately.',
    icon: SparklesIcon,
  },
  {
    name: 'Tailored tone controls',
    description:
      'Select from professional, academic, or conversational tones so every AI-generated answer matches your voice.',
    icon: ChatBubbleLeftRightIcon,
  },
  {
    name: 'Works for any workflow',
    description:
      'Use it as an AI short answer generator, customer support assistant, or answers generator for study guides.',
    icon: RocketLaunchIcon,
  },
  {
    name: 'Privacy-first defaults',
    description:
      'We never store your prompts. Upgrade to DocsBot for access controls, audit trails, and custom trained bots.',
    icon: ShieldCheckIcon,
  },
]

const useCases = [
  {
    title: 'Question Answering for Any Topic',
    description:
      'Submit any question and receive a clear, well-structured answer. Add optional context to tailor the response to your needs.',
    icon: AcademicCapIcon,
  },
  {
    title: 'Support and Customer Service',
    description:
      'Provide a customer query or support issue and get a helpful, context-aware answer in your preferred tone and format.',
    icon: CheckBadgeIcon,
  },
  {
    title: 'Documentation and FAQ Drafting',
    description:
      'Turn questions or issues into ready-to-use FAQ entries or help articles, using your own context for accuracy.',
    icon: ClipboardDocumentCheckIcon,
  },
  {
    title: 'Sales, Marketing, and Communication',
    description:
      'Input product or service questions and generate persuasive, informative answers tailored to your audience.',
    icon: LightBulbIcon,
  },
]

const steps = [
  {
    name: '1. Ask any question',
    description:
      'Enter your question or prompt. Add optional background context or source material to guide the AI answer generator.',
  },
  {
    name: '2. Choose tone & format',
    description:
      'Pick your preferred tone, answer length, and format so the AI-generated answers align with your brand or assignment.',
  },
  {
    name: '3. Generate & refine',
    description:
      'Click Generate Answer to receive polished results in seconds. Copy, download, or re-run the free AI answer generator until it is perfect.',
  },
]

const parseErrorResponse = async (response) => {
  const fallbackMessage = 'Something went wrong. Please try again later.'

  try {
    const responseText = await response.text()

    if (!responseText) {
      return fallbackMessage
    }

    try {
      const parsed = JSON.parse(responseText)
      if (typeof parsed === 'string') {
        return parsed
      }
      if (parsed && typeof parsed === 'object' && parsed.message) {
        return parsed.message
      }
    } catch (jsonError) {
      if (responseText.trim().length > 0) {
        return responseText
      }
    }
  } catch (error) {
    console.error('Failed to parse error response:', error)
  }

  return fallbackMessage
}

const AIAnswerGeneratorForm = () => {
  const [question, setQuestion] = useState('')
  const [context, setContext] = useState('')
  const [selectedTone, setSelectedTone] = useState(tones[0])
  const [selectedLength, setSelectedLength] = useState(answerLengths[1])
  const [selectedFormat, setSelectedFormat] = useState(formats[0])
  const [isGenerating, setIsGenerating] = useState(false)
  const [errorText, setErrorText] = useState('')
  const [generatedAnswer, setGeneratedAnswer] = useState(null)
  const [showSignupModal, setShowSignupModal] = useState(false)
  const [isCopied, setIsCopied] = useState(false)
  const posthog = usePostHog()
  const isFormDisabled = isGenerating

  const stats = useMemo(() => {
    if (!generatedAnswer?.text) return null
    const words = generatedAnswer.text.trim().split(/\s+/).filter(Boolean).length
    const characters = generatedAnswer.text.length
    const readingMinutes = Math.max(1, Math.round(words / 180))

    return {
      words,
      characters,
      readingMinutes,
    }
  }, [generatedAnswer])

  const processMarkdown = (text) => {
    return unified()
      .use(remarkParse)
      .use(remarkGfm)
      .use(remarkRehype)
      .use(rehypeStringify)
      .processSync(text)
      .toString()
  }

  const handleGenerate = async (event) => {
    event.preventDefault()

    if (!question.trim()) {
      setErrorText('Please add a question or prompt so our AI answer generator knows what to solve.')
      posthog?.capture('Free Tool', {
        tool: 'AI Answer Generator',
        action: 'Error',
        error: 'Empty question',
        category: 'Productivity',
      })
      return
    }

    setIsGenerating(true)
    setErrorText('')

    try {
      const endpoint = `/api/tools/text-prompter`
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          type: 'answer-generator',
          input: question,
          context,
          tone: selectedTone.name,
          answerLength: selectedLength.name,
          formatPreference: selectedFormat.name,
        }),
      })

      if (!response.ok) {
        if (response.status === 429) {
          setErrorText('Daily usage limit exceeded, please try again tomorrow or create a free DocsBot account for higher limits.')
          setShowSignupModal(true)
        } else {
          const errorMessage = await parseErrorResponse(response)
          setErrorText(errorMessage)
        }
        posthog?.capture('Free Tool', {
          tool: 'AI Answer Generator',
          action: 'Error',
          error: response.status,
          category: 'Productivity',
        })
        return
      }

      const data = await response.json()
      const textResponse = typeof data === 'string' ? data : Array.isArray(data) ? data.join('\n\n') : JSON.stringify(data)

      setGeneratedAnswer({
        text: textResponse,
        html: processMarkdown(textResponse),
      })

      posthog?.capture('Free Tool', {
        tool: 'AI Answer Generator',
        action: 'Generated Answer',
        tone: selectedTone.name,
        length: selectedLength.name,
        format: selectedFormat.name,
        category: 'Productivity',
      })
    } catch (error) {
      console.error('AI Answer Generator error:', error)
      setErrorText('Unexpected error generating your answer. Please try again.')
      posthog?.capture('Free Tool', {
        tool: 'AI Answer Generator',
        action: 'Error',
        error: error.message,
        category: 'Productivity',
      })
    } finally {
      setIsGenerating(false)
    }
  }

  const handleCopy = async () => {
    if (!generatedAnswer?.text) return
    try {
      await navigator.clipboard.writeText(generatedAnswer.text)
      setIsCopied(true)
      setTimeout(() => setIsCopied(false), 2000) // Reset after 2 seconds
      posthog?.capture('Free Tool', {
        tool: 'AI Answer Generator',
        action: 'Copied Answer',
        category: 'Productivity',
      })
    } catch (error) {
      console.error('Copy failed', error)
    }
  }

  return (
    <div className="mt-12 overflow-hidden rounded-3xl bg-white shadow-xl">
      {generatedAnswer ? (
        <div className="p-8">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <h3 className="text-lg font-semibold text-gray-900">AI Generated Answer</h3>
            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={() => setGeneratedAnswer(null)}
                className="inline-flex items-center gap-2 rounded-md bg-gray-100 px-3 py-2 text-sm font-medium text-gray-600 shadow-sm ring-1 ring-inset ring-gray-200 transition hover:bg-gray-200"
              >
                Generate New Answer
              </button>
              <button
                type="button"
                onClick={handleCopy}
                className="inline-flex items-center gap-2 rounded-md bg-white px-3 py-2 text-sm font-medium text-gray-600 shadow-sm ring-1 ring-inset ring-gray-200 transition hover:bg-gray-100"
              >
                {isCopied ? (
                  <CheckIcon className="h-5 w-5 text-green-600" />
                ) : (
                  <ClipboardDocumentIcon className="h-5 w-5" />
                )}
                {isCopied ? 'Copied!' : 'Copy'}
              </button>
            </div>
          </div>

          <div className="mt-5 rounded-xl border border-yellow-200 bg-yellow-50 p-4 text-sm text-yellow-900">
            <div className="">
              <div className="flex items-start gap-3">
                <ExclamationTriangleIcon className="mt-0.5 h-6 w-6 text-yellow-500" />
                <div>
                  <p className="font-semibold">Review AI-generated answers before using</p>
                  <p className="mt-1">
                    AI can hallucinate and make up answers, especially for topics that are not well known such as your business or product. Train a custom AI answer agent on your own content and documentation for accurate, grounded answers with sources.
                  </p>
                </div>
              </div>
              <Link
                href="/register"
                className="mt-4 ms-6 inline-flex items-center justify-center rounded-md bg-cyan-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-cyan-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-600"
              >
                Create a Free DocsBot Answer Generator
              </Link>
            </div>
          </div>

          {stats && (
            <p className="mt-3 text-xs text-gray-500">
              {stats.words} words · {stats.characters} characters · ~{stats.readingMinutes} min read · {selectedTone.emoji}{' '}
              {selectedTone.name} tone · {selectedLength.name} length · {selectedFormat.name}
            </p>
          )}

          <article
            className="prose mt-5 max-w-none text-gray-800 prose-headings:text-gray-900 prose-a:text-cyan-600"
            dangerouslySetInnerHTML={{ __html: generatedAnswer.html }}
          />
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-5">
          <div className="border-b border-gray-200 bg-gray-50 p-8 lg:col-span-2 lg:border-r">
            <h2 className="text-lg font-semibold text-gray-900">Customize your answer</h2>
            <p className="mt-2 text-sm text-gray-500">
              Choose tone, answer length, and structure so the AI-generated answer matches your exact needs.
            </p>

            <div className="mt-6 space-y-6">
              <div>
                <h3 className="text-sm font-semibold text-gray-700">Select Tone</h3>
                <div className="mt-3 grid gap-3">
                  {tones.map((tone) => {
                    const isActive = tone.name === selectedTone.name
                    return (
                      <button
                        key={tone.name}
                        type="button"
                        onClick={() => setSelectedTone(tone)}
                        disabled={isFormDisabled}
                        className={`flex items-start rounded-xl border p-3 text-left transition ${
                          isActive ? 'border-cyan-500 bg-cyan-50 shadow-sm' : 'border-gray-200 hover:border-gray-300'
                        } disabled:opacity-75 disabled:cursor-not-allowed disabled:pointer-events-none`}
                      >
                        <span className="mr-3 text-2xl" aria-hidden>
                          {tone.emoji}
                        </span>
                        <span>
                          <span className="block text-sm font-semibold text-gray-900">{tone.name}</span>
                          <span className="mt-1 block text-sm text-gray-500">{tone.description}</span>
                        </span>
                      </button>
                    )
                  })}
                </div>
              </div>

              <div>
                <h3 className="text-sm font-semibold text-gray-700">Answer Length</h3>
                <div className="mt-3 grid gap-3">
                  {answerLengths.map((length) => {
                    const isActive = length.name === selectedLength.name
                    return (
                      <button
                        key={length.name}
                        type="button"
                        onClick={() => setSelectedLength(length)}
                        disabled={isFormDisabled}
                        className={`rounded-xl border p-3 text-left transition ${
                          isActive ? 'border-cyan-500 bg-cyan-50 shadow-sm' : 'border-gray-200 hover:border-gray-300'
                        } disabled:opacity-75 disabled:cursor-not-allowed disabled:pointer-events-none`}
                      >
                        <span className="block text-sm font-semibold text-gray-900">{length.name}</span>
                        <span className="mt-1 block text-sm text-gray-500">{length.description}</span>
                      </button>
                    )
                  })}
                </div>
              </div>

              <div>
                <h3 className="text-sm font-semibold text-gray-700">Format Preference</h3>
                <div className="mt-3 grid gap-3">
                  {formats.map((format) => {
                    const isActive = format.name === selectedFormat.name
                    return (
                      <button
                        key={format.name}
                        type="button"
                        onClick={() => setSelectedFormat(format)}
                        disabled={isFormDisabled}
                        className={`rounded-xl border p-3 text-left transition ${
                          isActive ? 'border-cyan-500 bg-cyan-50 shadow-sm' : 'border-gray-200 hover:border-gray-300'
                        } disabled:opacity-75 disabled:cursor-not-allowed disabled:pointer-events-none`}
                      >
                        <span className="block text-sm font-semibold text-gray-900">{format.name}</span>
                        <span className="mt-1 block text-sm text-gray-500">{format.description}</span>
                      </button>
                    )
                  })}
                </div>
              </div>
            </div>
          </div>

          <form onSubmit={handleGenerate} className="p-8 lg:col-span-3">
            {errorText && <Alert type="error" title="" text={errorText} className="mb-6" />}
            <div>
              <label htmlFor="question" className="text-sm font-semibold text-gray-700">
                Question or Prompt
              </label>
              <textarea
                id="question"
                name="question"
                rows={5}
                className="mt-2 w-full rounded-lg border border-gray-300 p-3 text-sm shadow-sm focus:border-cyan-500 focus:outline-none focus:ring-2 focus:ring-cyan-500/40 disabled:opacity-75 disabled:cursor-not-allowed"
                placeholder="Ask anything: e.g. 'Explain quantum computing in simple terms' or 'Draft an answer for our refund policy question'."
                value={question}
                onChange={(event) => setQuestion(event.target.value)}
                disabled={isFormDisabled}
              />
            </div>

            <div className="mt-6">
              <label htmlFor="context" className="text-sm font-semibold text-gray-700">
                Optional Context or Source Material
              </label>
              <textarea
                id="context"
                name="context"
                rows={4}
                className="mt-2 w-full rounded-lg border border-gray-300 p-3 text-sm shadow-sm focus:border-cyan-500 focus:outline-none focus:ring-2 focus:ring-cyan-500/40 disabled:opacity-75 disabled:cursor-not-allowed"
                placeholder="Paste background notes, documentation excerpts, or grading rubrics so the answer generator AI can stay aligned."
                value={context}
                onChange={(event) => setContext(event.target.value)}
                disabled={isFormDisabled}
              />
            </div>

            <button
              type="submit"
              className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-cyan-600 px-4 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-cyan-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-600 disabled:opacity-75 disabled:cursor-not-allowed disabled:pointer-events-none"
              disabled={isFormDisabled}
            >
              {isGenerating ? (
                <>
                  <LoadingSpinner />
                  <LoadingText />
                </>
              ) : (
                'Generate Answer'
              )}
            </button>

            <CarbonAd className="mt-6 flex justify-center" />
          </form>
        </div>
      )}

      <ToolsSignupModal
        open={showSignupModal}
        setOpen={setShowSignupModal}
        toolName="AI Answer Generator"
        toolCategory="Productivity"
      />
    </div>
  )
}

export default function AIAnswerGeneratorPage({ starRatingData }) {
  return (
    <>
      <NextSeo
        title="AI Answer Generator Free | GPT-5 Accurate Answers With No Sign-Up"
        description="Use our GPT-5 AI answer generator free to craft instant, high-quality responses for any question. Choose tone, format, and length to match your needs—no login required."
        canonical="https://docsbot.ai/tools/productivity/ai-answer-generator"
        openGraph={{
          url: 'https://docsbot.ai/tools/productivity/ai-answer-generator',
          title: 'AI Answer Generator Free | GPT-5 Accurate Answers With No Sign-Up',
          description:
            'Generate accurate GPT-5 answers instantly with our online AI answer generator. Perfect for study, support, and knowledge base workflows.',
          images: [
            {
              url: 'https://docsbot.ai/images/og/ai-answer-generator.png',
              alt: 'DocsBot Free AI Answer Generator Tool',
            },
          ],
        }}
      />
      <FAQPageJsonLd
        mainEntity={faqs.map((faq) => ({
          questionName: faq.question,
          acceptedAnswerText: faq.answer,
        }))}
      />
      <Header />
      <main>
        <div className="relative isolate bg-gray-900">
          <div
            className="absolute inset-x-0 top-0 -z-10 transform-gpu overflow-hidden blur-3xl"
            aria-hidden="true"
          >
            <div
              className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#34d399] to-[#38bdf8] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
              style={{
                clipPath:
                  'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)',
              }}
            />
          </div>
          <div className="py-16 sm:py-28">
            <div className="mx-auto max-w-5xl px-6 text-center">
              <span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-1 text-sm font-medium text-cyan-200">
                <SparklesIcon className="h-4 w-4" /> Free AI Answer Generator · Powered by GPT-5 · No Signup Required
              </span>
              <h1 className="mt-6 text-4xl font-bold tracking-tight text-white sm:text-6xl">
                AI Answer Generator - Free Answers to Any Question
              </h1>
              <p className="mt-6 text-lg leading-8 text-gray-300">
                Our AI answer generator delivers clear answers, explanations, step-by-step walkthroughs, and persuasive narratives on demand. Optimize study sessions, support workflows, and marketing content with a free answer generator AI that requires no login.
              </p>
              <div className="mt-8 flex flex-wrap justify-center gap-4 text-sm text-cyan-100">
                <span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2">
                  <InformationCircleIcon className="h-4 w-4" /> AI generator for questions and answers
                </span>
                <span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2">
                  <InformationCircleIcon className="h-4 w-4" /> Online AI answer generator
                </span>
                <span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2">
                  <InformationCircleIcon className="h-4 w-4" /> Free AI answer creator no sign up
                </span>
              </div>
            </div>
            <div className="mx-auto mt-12 max-w-6xl px-6">
              <AIAnswerGeneratorForm />
            </div>
              <StarRating
                itemId="ai-answer-generator"
                name="AI Answer Generator - DocsBot"
                className="mx-auto mt-10 flex justify-center text-white"
                starRatingData={starRatingData}
              />
          </div>
        </div>

        <RegisterCTA
          customTitle="Launch your own AI answer generator in minutes"
          description="Create a DocsBot trained on your website or documentation, then embed it anywhere to share accurate answers with customers and teammates."
          button="Create your Free DocsBot Answer Generator"
        />

        <section className="bg-white py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-base font-semibold leading-7 text-cyan-600">Why DocsBot AI Answer Generator?</h2>
              <p className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
                The AI answer generator built for business productivity and customer support
              </p>
              <p className="mt-6 text-lg leading-8 text-gray-600">
                Built on the enterprise-grade GPT-5 AI model with reasoning, our answer generator adapts to every workflow—from AI test answer generator needs to customer knowledge bases and product enablement.
              </p>
            </div>
            <dl className="mx-auto mt-16 grid max-w-4xl grid-cols-1 gap-10 sm:grid-cols-2">
              {benefits.map((benefit) => (
                <div key={benefit.name} className="rounded-2xl border border-gray-200 p-6">
                  <benefit.icon className="h-10 w-10 text-cyan-600" />
                  <dt className="mt-4 text-lg font-semibold text-gray-900">{benefit.name}</dt>
                  <dd className="mt-3 text-sm leading-6 text-gray-600">{benefit.description}</dd>
                </div>
              ))}
            </dl>
          </div>
        </section>

        <section className="bg-gray-50 py-24 sm:py-32">
          <div className="mx-auto max-w-6xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-base font-semibold leading-7 text-cyan-600">How it works</h2>
              <p className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
                Generate answers faster than ever
              </p>
              <p className="mt-6 text-lg leading-8 text-gray-600">
                Follow three simple steps to turn any question into a polished AI generated answer.
              </p>
            </div>
            <dl className="mx-auto mt-16 grid max-w-4xl grid-cols-1 gap-12 sm:grid-cols-3">
              {steps.map((step) => (
                <div key={step.name} className="rounded-2xl bg-white p-6 shadow-sm">
                  <dt className="text-lg font-semibold text-gray-900">{step.name}</dt>
                  <dd className="mt-3 text-sm leading-6 text-gray-600">{step.description}</dd>
                </div>
              ))}
            </dl>
          </div>
        </section>

        <section className="bg-white py-24 sm:py-32">
          <div className="mx-auto max-w-6xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-base font-semibold leading-7 text-cyan-600">Versatile answer generator AI use cases</h2>
              <p className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
                Designed for students, support teams, marketers, and product experts
              </p>
              <p className="mt-6 text-lg leading-8 text-gray-600">
                Whether you need an AI short answer generator for quizzes or a long-form AI generator question and answer companion, DocsBot keeps every response on brand.
              </p>
            </div>
            <dl className="mx-auto mt-16 grid max-w-5xl grid-cols-1 gap-10 lg:grid-cols-2">
              {useCases.map((useCase) => (
                <div key={useCase.title} className="rounded-2xl border border-gray-200 bg-gray-50 p-6">
                  <useCase.icon className="h-10 w-10 text-cyan-600" />
                  <dt className="mt-4 text-xl font-semibold text-gray-900">{useCase.title}</dt>
                  <dd className="mt-3 text-sm leading-6 text-gray-600">{useCase.description}</dd>
                </div>
              ))}
            </dl>
          </div>
        </section>

        <section className="bg-gray-900 py-24 sm:py-32">
          <div className="mx-auto max-w-4xl px-6 text-center text-white">
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">AI answer generator FAQs</h2>
            <p className="mt-4 text-lg text-gray-300">
              Everything you need to know about our free AI answer generator, including privacy, accuracy, and DocsBot upgrades.
            </p>
            <div className="mt-10 space-y-6 text-left">
              {faqs.map((faq) => (
                <div key={faq.question} className="rounded-2xl bg-white/5 p-6">
                  <h3 className="text-xl font-semibold text-white">{faq.question}</h3>
                  <p className="mt-3 text-sm leading-6 text-gray-200">{faq.answer}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <div className="mx-auto max-w-7xl px-6 py-16 lg:px-8">
          <FreeToolsGrid category="Productivity" />
        </div>
      </main>
      <Footer />
    </>
  )
}

export const getStaticProps = async () => {
  const starRatingData = await getRating('ai-answer-generator')

  return {
    props: { starRatingData },
    revalidate: 86400,
  }
}
